# Generated by Django 4.2.11 on 2025-03-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainnee', '0002_alter_trainee_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
